hub:
  image: selenium/hub:${GRID_VERSION}
  ports:
    - "4445:4444"
  environment:
    - GRID_TIMEOUT=30
    - GRID_MAX_SESSION=6
    - GRID_BROWSER_TIMEOUT=30
chrome:
  image: selenium/node-chrome-debug:${GRID_VERSION}
  ports:
    - "5900:5900"
  links:
    - hub
  environment:
    - NODE_MAX_SESSION=1
    - NODE_MAX_INSTANCES=1
  volumes:
    - /dev/shm:/dev/shm
